use_frameworks!

platform :ios, '14.0'

target 'SwiftlyPresent_Example' do
  pod 'SwiftlyPresent', :path => '../'
  pod 'CombineCocoa'
  target 'SwiftlyPresent_Tests' do
    inherit! :search_paths

    
  end
end
