# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'SwiftlyPresentApp' do
  use_frameworks!
  
  pod 'CombineCocoa'
  pod 'SwiftlyPresent', :path => './'


end
